### ISSUE TITLE
Introduce Scaffold lint to remind contentPadding usage

### ISSUE THREAD

**Issue by srcenchen** [kiwicom/orbit-compose#103]
When I use Scaffold in orbit for compose, i found a bug in it.  
![image](https://user-images.githubusercontent.com/48435089/157584168-3bf9cca5-4d9b-4610-a7ed-55e04aece464.png)  
However, it's not working well, like this.  
![image](https://user-images.githubusercontent.com/48435089/157584240-7ff2e31c-5fb5-4224-a848-fcf6cf794cec.png)
The topAppBar is override my Alert.  
But, When i use Scaffold in compose. It's woking well  
![image](https://user-images.githubusercontent.com/48435089/157584478-19036bf0-2d76-403d-b1a5-0f207ec93608.png)
![image](https://user-images.githubusercontent.com/48435089/157584503-63fb1779-7529-4c39-9540-1f81c5522c01.png)

Config :
Jetpack Compose 1.2.0 alpha-03

**Comment by hrach** [comment]
Hi, thanks for reporting. This is currently intentional, as it is required to "utilize" passed content padding like this:

```kotlin
Scaffold(
   appBar = {},
) { contentPadding -> 
  Column(Modifier.padding(contentPadding)) {}
  // or
  LazyColumn(contentPadding = contentPadding)
}
```

However, thanks for Material's example -- we wanna be "compatible" with its approach, **so I'm gonna let this open to change the behavior to match Material.**

**Comment by srcenchen** [comment]
> Hi, thanks for reporting. This is currently intentional, as it is required to "utilize" passed content padding like this:
> 
> ```kotlin
> Scaffold(
>    topBar = {},
> ) { contentPadding -> 
>   Column(Modifier.padding(contentPadding)) {}
>   // or
>   LazyColumn(contentPadding = contentPadding)
> }
> ```
> 
> However, thanks for Material's example -- we wanna be "compatible" with its approach, **so I'm gonna let this open to change the behavior to match Material.**
> 

ok, i konw.
Thanks

**Comment by hrach** [comment]
Hi, Material 3 has the behavior now, so what we're planning here is to add a Lint to let you know that contentPadding should be used.
