### ISSUE TITLE
Size modifiers don't work on ClickableField

### ISSUE THREAD

**Issue by rex1234** [kiwicom/orbit-compose#120]
e.g. when setting Modifier.fillMaxWidth()

**Comment by hrach** [comment]
@rex1234 please could you post an example that doesn't work?

**Comment by rex1234** [comment]
You can try this:
```
  Column(
    modifier = Modifier
      .padding(16.dp)
      .fillMaxWidth(),
    verticalArrangement = Arrangement.spacedBy(16.dp),
  ) {

    TextField(
      modifier = Modifier.fillMaxWidth(),
      value = "Test",
      onValueChange = { },
    )

    ClickableField(
      modifier = Modifier.fillMaxWidth(),
      value = "Test",
      onClick = { },
    )
  }
```
The TextField correctly fills the width but the field only wraps its content (I think it's due to wrong modifier propagation).
![image](https://user-images.githubusercontent.com/5604351/159689607-77834cdf-17b0-4022-8ca8-0a84a8bb0070.png)
