### ISSUE TITLE
`Tile` component

### ISSUE THREAD

**Issue by shalva97** [kiwicom/orbit-compose#138]
Hi, thanks for those awesome composables.

On [your website](https://orbit.kiwi/components/structure/tile/) there is a Tile component which on android has green dot with thext "Released". Where can I find it? typing `Tile` in Android Studio gives autocompletions for `ChoiceTile` and `ChoiceTileCentered`

**Comment by hrach** [comment]
Hi, thanks for opening this. This is a mistake)bug. We don't have it for now. Sorry bout that.

There are some undergoing design changes in this area so I can't comment on the exact timeline. I'll check and get back to you

**Comment by hrach** [comment]
Status should be fixed by this: https://github.com/kiwicom/orbit/pull/3365

As the component itself, it seems it is still in our backlog as it is in figma.
