### ISSUE TITLE
Update to Compose 1.2

### ISSUE THREAD

**Issue by hrach** [kiwicom/orbit-compose#145]

**Comment by shalva97** [comment]
This got me thinking.... In my project I have compose v1.2.0-beta03, this lib has 1.1.1. Will I see some undefined behavior or crashes? so far have not seen any....

**Comment by hrach** [comment]
It is ok to use Compose Compiler 1.2 for compiling and using compose runtime libs 1.1. That shouldn't be an issue.

The same way using Compose 1.2 runtime libs is ok for stable API from Compose 1.1. But, we also use some unstable API from Compose 1.1, so there is no guarantee that using Compose 1.2 won't crash with this lib.

Saying that we ack this is not ideal situation though Compose is currently in state that it is not realistic to use only stable API.

As for Compose 1.2 timeline we will update to it with first RC. I.e. quite soon.
