### ISSUE TITLE
Problem with ChoiceTile Icon

### ISSUE THREAD

**Issue by Nodrex** [kiwicom/orbit-compose#146]
I am trying to set icon to ChoiceTile , but it does not works:

`@Composable
fun CreateKiwiUI() {
    var selected by remember {
        mutableStateOf(false)
    }
    
    Column() {
        ChoiceTile(
            icon = {
                painterResource(id = R.drawable.ic_correct)
            },
            selected = selected,
            onSelect = {
                selected = !selected
            },
            showRadio = true,
            content = {
                Text(text = "Some text")
            }
        )
    }
}`

lib versions:
implementation "kiwi.orbit.compose:ui:0.13.0"
implementation "androidx.compose.ui:ui:1.2.0-beta01"
implementation "androidx.compose.material:material:1.2.0-beta01"
I even tried latest release version of compose 1.1.1 but still does not works

**Comment by hrach** [comment]
Hi @nodrex, the icon slot argument accepts full composable slot, not just painter. I.e. you should use Image/Icon composable there.

```kotlin
Column() {
    ChoiceTile(
        icon = {
            Icon(painterResource(id = R.drawable.ic_correct))
        },
        selected = selected,
        onSelect = {
            selected = !selected
        },
        showRadio = true,
        content = {
            Text(text = "Some text")
        }
    )
}
```
You can see usage here: https://github.com/kiwicom/orbit-compose/blob/aa40abefe58fe04bb785054886814641b922ab5a/catalog/src/main/java/kiwi/orbit/compose/catalog/screens/ChoiceTileScreen.kt

**Comment by Nodrex** [comment]
Thanks, @hrach  for the quick replay.
Is there any documentation specifically for Android besides Examples?

**Comment by hrach** [comment]
For now there is only the catalog app. Soon we will merge Previews for particular components. https://orbit.kiwi documentation is planned, but not in near days/weeks.
