### ISSUE TITLE
Default argument for contentDescriptin

### ISSUE THREAD

**Issue by shalva97** [kiwicom/orbit-compose#149]
I have always met those warnings asking me to add some descriptions to ImageViews, same is for Composables. Do you guys regulary set them up? Personaly, I always ignore them, or just pass nulls everywhere... 

So since we have wrappers around `Image` and `Icon` why not add default parameter for `contentDescription: String? = null`? I can send PR if you consider it

**Comment by hrach** [comment]
>  Do you guys regulary set them up?

Not much, but that's not something we're proud of. Actually, our long-term is to make accessibility better in our app. The main reason not to have a default value is to let us think of those images / icons, if there is or isn't an alternative text that says what it is. 

E.g. search icon in text field does not need content description if there is a Label/Placeholder saying it is a "search" field.

Anyway, having this compulsory makes us think about that and we consider this a good option.
