### ISSUE TITLE
Card composable is not properly shown on dark theme

### ISSUE THREAD

**Issue by shalva97** [kiwicom/orbit-compose#163]
on white theme it is all pretty but on dark theme it is not visible at all

dark theme | light theme
--- | ---
![Screenshot_20220606-222627_JellyList](https://user-images.githubusercontent.com/22417494/172222945-16c58718-2ba9-46aa-ab48-3f1a92952d0c.png) | ![Screenshot_20220606-222601_JellyList](https://user-images.githubusercontent.com/22417494/172222955-5fe0e18c-403b-46ee-b1f2-762f3e26ccb1.png)

Sorry about toast, im lazy to screenshot it again. Anyways as you can see the Card composable's shadow is barly noticable compared to light theme variant

**Comment by hrach** [comment]
Yes, this is a known limitation. Orbit Compose is currently only dark-mode aware, not ready. We are preparing for that time, though there is no Orbit design support yet. We may introduce Material's way of surface highlight in between.

**Comment by hrach** [comment]
This is fixed by #195. Please open a new issue if there is something to fix in dark mode.
