### ISSUE TITLE
[Icon request] add an icon for password

### ISSUE THREAD

**Issue by shalva97** [kiwicom/orbit-compose#169]
Correct me if i missed but could not find it.

There is already `Icons.AccountCircle` so I think also adding password icon would make a nice pair for login screens!

For example:
![image](https://user-images.githubusercontent.com/22417494/173905939-26f90361-4c4b-418b-8251-209259f9d8cc.png)

**Comment by hrach** [comment]
Isn't icon sercuity enough? :D ;) 
![image](https://user-images.githubusercontent.com/284263/173908083-6e3ad1dd-249b-4687-b8ef-f81ad9fe6a85.png)
