### ISSUE TITLE
Indeterminate progressbar

### ISSUE THREAD

**Issue by Nodrex** [kiwicom/orbit-compose#179]
There is not ability to use `LinearProgressIndicator` as indeterminate  and i was not able to find other one to use as indeterminate

**Comment by hrach** [comment]
Yeah, we don't use it though we should add it. We instead use some shimmer/placeholers effects.

**Comment by Nodrex** [comment]
Are you planning to implement an Indeterminate progress bar?

**Comment by Drekorian** [comment]
@hrach, @Nodrex, I think we could reuse the animation definition from Material design and port it into our component.
