### ISSUE TITLE
Unify `icon` slots

### ISSUE THREAD

**Issue by Drekorian** [kiwicom/orbit-compose#203]
Composables with nullable `icon` slot:

- `ChoiceTile`,
- `ChoiceTileCentered`,
- `ClickableField`,
- `PasswordTextField`,
- `SelectField`,
- `TextField` and
- `FieldContent`.

Composables with non-null `icon` slot:

- `ListChoice`,
- `PillButton`,
- `TopAppBar`,
- `TopAppBarLarge` and
- `FieldIcon`.

@hrach, please review as mentioned in https://github.com/kiwicom/orbit-compose/pull/201#discussion_r932011182.

**Comment by hrach** [comment]
Basically, it is not only about icon slots, but all slots. Anyway, we need the null to do some advance composition so the answer is:
-   ChoiceTile - yes
-   ChoiceTileCentered - yes
-   ClickableField - no
-   PasswordTextField - no
-   SelectField - no
-   TextField - no
-   FieldContent - no
