### ISSUE TITLE
Whats benefit of having .idea folder in Git?

### ISSUE THREAD

**Issue by shalva97** [kiwicom/orbit-compose#257]
I always get random file changes and I dont even know what they are. 

Currently there is a change in Project_default.xml. Should that even happen? in my experience, no matter what is added to .gitignore some random new file appears out of nowhere

There are few files for codeStyles but is not that already set as default by Intellij? 

How do you prevent future changes to these files on your side? or how do you handle conflicts? now I have something like this
![Screenshot 2022-10-08 at 22 26 16](https://user-images.githubusercontent.com/22417494/194722146-fe81c308-cede-4df4-b35d-2a7e9c7cedd9.png)

**Comment by Drekorian** [comment]
Well, in case of this particular file, it serializes and persists the inspection profile settings. In case you don't want to use the default one, go to `Settings -> Editor -> Inspections`, tap the gear icon and select _Duplicate..._. Save your custom inspection profile under any name and then add `.idea/inspectionProfiles/my_inspection_profile.xml` and `profiles_settings.xml` to your locally ignored files via either:

- using `git update-index --skip-worktree [<file>...]` (preferred) or
- using `git update-index --assume-unchanged [<file>...]`.
