### ISSUE TITLE
When I use orbit TextField, the layout will be push up

### ISSUE THREAD

**Issue by srcenchen** [kiwicom/orbit-compose#283]
When I use orbit TextField, the layout will be push up, However, When I use Material TextField, it's will be fine.  
here is the screenshot with closing the keyboard
![image](https://user-images.githubusercontent.com/48435089/201309848-73c0d24f-ea6c-48d3-952a-e7eff1a632f0.png)
here is the screenshot with opening the keyboard in orbit TextFiled
![image](https://user-images.githubusercontent.com/48435089/201309770-6e32f905-b342-4e62-8a53-b0979ddabc82.png)
here is the screenshot with opening the keyboard in Material TextFiled
![image](https://user-images.githubusercontent.com/48435089/201309910-d1a7b61a-9833-4434-a296-46f1e2cd7a1c.png)
And I notice a intersting thing, when I remove _WindowCompat.setDecorFitsSystemWindows(window, false)_ it's all right, but the Immersive status bar will be invalid
Codes like this
![image](https://user-images.githubusercontent.com/48435089/201310001-c2d16533-7c98-4115-bdb1-cee37053ef3b.png)

**Comment by YOUSSEFELJAYAD** [comment]
Try to remove the first padding (16.dp), and keep only the second padding (it),

**Comment by srcenchen** [comment]
> 

I have removed it, but it not be sloved

**Comment by srcenchen** [comment]
@YOUSSEFELJAYAD I have removed it, but it not be sloved

**Comment by srcenchen** [comment]
![image](https://user-images.githubusercontent.com/48435089/201335691-730fdd6d-a248-4573-9d74-10624dee86bd.png)
![image](https://user-images.githubusercontent.com/48435089/201335741-f67d5b7b-af54-4ff5-a99b-8f6abfb28ae6.png)

**Comment by srcenchen** [comment]
device-2022-11-11-200328.mp4

**Comment by srcenchen** [comment]
https://user-images.githubusercontent.com/48435089/201336817-89602361-c12d-4308-8ae2-f40d1ce218e7.mp4

**Comment by srcenchen** [comment]
The video is that I remove the topAppbar

**Comment by hrach** [comment]
What is the ProvideWindowInsets - is that the accompanist version? That should not be needed since Compose 1.2, if I'm not mistaken.

**Comment by srcenchen** [comment]
@hrach Yeah, I have removed it, I used it about 3 months ago,.But, When I removed it, The issue didn't be sloved

**Comment by srcenchen** [comment]
![image](https://user-images.githubusercontent.com/48435089/201339166-6a612d0c-fed7-4955-ad8e-b8328971c686.png)
Here is the Theme File

**Comment by hrach** [comment]
not sure it is the problem but the setDecor should be called outside compose in onCreate.

**Comment by srcenchen** [comment]
When I move the setDecor outside compose in onCreate, It does work

**Comment by YOUSSEFELJAYAD** [comment]
Try to see this ,
https://google.github.io/accompanist/insets/

**Comment by hrach** [comment]
yes, it shouldn't be set so "late" 👍 . so closing here.
