### ISSUE TITLE
Application crash - closes automatically when the appropriate steps are taken

### ISSUE THREAD

**Issue by olekstomek** [kiwicom/orbit-compose#340]
Steps to reproduce:
1. Go to `Select Field`
2. Select any value from the list 
3. Tap the back arrow in the upper left corner or the Android navigation back button
4. The application closes itself.
I expect to go back to the previous activity (main application activity) as in other cases.

Android 11, Xiaomi Mi 9, version of application 0.24.0

**Comment by hrach** [comment]
Thx. Reproduced. I'll take a look.

**Comment by hrach** [comment]
It was "just" a catalog issue. Fixed :)

**Comment by olekstomek** [comment]
That's great! :)
