### ISSUE TITLE
Missing Icons and Illustrations

### ISSUE THREAD

**Issue by DavidGrygar** [kiwicom/orbit-compose#353]
In 0.25.1 I can't see icons and illustrations in catalog.

**Comment by Drekorian** [comment]
Here's what I have found out so far. It's an issue with R8 which keeps the getter `@Composable`s (`getAccommodation()`, `getAirHelp()`, ...) but strips the Kotlin Metadata. This means, it's not properly identifying them as  Kotlin properties. This means reflective property `memberProperties` used in `IconsScreen.kt` won't pick them up.

Switching to [com.android.tools.r8-4.0.48](https://maven.google.com/web/index.html?q=r8#com.android.tools:r8:4.0.48) fixed the issue, however I can't make the project sync in the Android Studio, I assume some Android Build Tools version mismatch).

**Comment by hrach** [comment]
Wouldn't the latest 3 version (3.3.75) fix that as well?

**Comment by Drekorian** [comment]
Unfortunately, I have the same results for 3.3.75 as current production.

**Comment by Drekorian** [comment]
Confirmed. Please release a new version into Play Store and close this issue.
