### ISSUE TITLE
Update ButtonLinks design/sizing

### ISSUE THREAD

**Issue by hrach** [kiwicom/orbit-compose#472]
![obrazek](https://github.com/kiwicom/orbit-compose/assets/284263/3f239e9d-f36b-4145-a323-01d5f88054ac)

**Comment by yveskalume** [comment]
I'd like to work on some issues, and it'll be great to have some descriptions

**Comment by hrach** [comment]
Closing as the current approach seems to be a step back and Orbit is reconsidering the metrics.
